name: Deploy Vue project to GitHub Pages

on:
  push:
    branches: ['master']   # 你的主分支名

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web   # 进入 web 目录执行命令
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Clean cache and dist
      run: |
        rm -rf dist node_modules/.vite
      working-directory: ./web

    - name: Install dependencies
      run: npm ci
      working-directory: ./web

    - name: Build project
      run: npm run build
      working-directory: ./web

    - name: Check index.html base path
      run: cat dist/index.html | grep -o 'src="/[^"]*"'
      working-directory: ./web

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4